import userRoute from "./userRoutes.js";
import UserRepository from "./userRepository.js";
import { db } from "../../db/db.js";
import UserService from "./userService.js";
import UserHandler from "./userHandler.js";
import StorageService from "../../services/logger/storage/storage.js";
import ResizeService from "../../services/resize/resize.js";
const storageService = new StorageService(new ResizeService());
const user = new UserRepository(db());
const userService = new UserService(user, storageService);
const userHandler = new UserHandler(userService);
export default userRoute(userHandler);
